{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "registry-regulation-management.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "registry-regulation-management.labels" . | nindent 4 }}
{{- end }}
